import mongoose from 'mongoose';
import './User.js';
import './TestCatalog.js';
import './LabCenter.js';
import './Doctor.js';
import './Rider.js';

const referralSourceSubSchema = new mongoose.Schema(
  {
    type: {
      type: String,
      enum: ['partner', 'external', 'none'],
      default: 'none',
    },
    partnerDoctorId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Doctor',
      default: null,
    },
    externalText: {
      type: String,
      trim: true,
      default: null,
    },
  },
  { _id: false }
);

/**
 * A SNAPSHOT of the collection address, not a reference.
 *
 * The rider navigates to wherever the patient was when they booked. If this
 * held an addressId and the patient later edited or deleted that address, an
 * in-flight job would silently change destination or lose it entirely. The
 * source id is kept for traceability only.
 */
const collectionAddressSubSchema = new mongoose.Schema(
  {
    addressId: { type: mongoose.Schema.Types.ObjectId, ref: 'Address', default: null },
    label: { type: String, trim: true, default: null },
    line: { type: String, trim: true, required: true },
    pincode: { type: String, trim: true, required: true },
    lat: { type: Number, required: true },
    lng: { type: Number, required: true },
  },
  { _id: false }
);

const bookingSchema = new mongoose.Schema(
  {
    patientId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },
    familyMemberId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'FamilyMember',
      default: null,
    },
    testIds: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'TestCatalog',
      },
    ],
    /**
     * Packages are TestCatalog rows with `category: 'package'` — that is how
     * they are seeded, how the catalogue serves them, and how bookingService
     * resolves them (findTestById / findTestBySlug).
     *
     * This declared `ref: 'TestPackage'`, a parallel model nothing ever writes
     * to. Mongoose picks the model from the ref, so every populate of this
     * field searched an empty collection and returned null: a booked package
     * silently lost its name everywhere it was displayed.
     */
    /**
     * The checkup packages in this booking.
     *
     * Was a single `packageId`, which could not express a basket holding two
     * checkups — those had to be filed as ordinary test lines, priced
     * correctly but losing the "this was a package" label everywhere it was
     * shown: the rider's job card, the lab queue, the doctor's view.
     *
     * Packages are TestCatalog rows like any other item, so this changes what
     * a booking RECORDS, never what it costs — the price is the sum of every
     * item's basePrice either way.
     *
     * Subscription.packageId stays singular on purpose: a subscription is one
     * package on a cycle, not a basket.
     */
    packageIds: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'TestCatalog',
      },
    ],
    labCenterId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'LabCenter',
      required: true,
      index: true,
    },
    mode: {
      type: String,
      enum: ['home', 'visit'],
      required: true,
    },
    slotDateTime: {
      type: Date,
      required: true,
    },
    status: {
      type: String,
      enum: [
        'pending',
        'rider_assigned',
        'en_route',
        'collected',
        'at_lab',
        'report_ready',
        'awaiting_confirm',
        'confirmed',
        'sample_collected', // legacy alias
        'processing',
        'completed',
        'cancelled',
      ],
      default: 'pending',
    },
    assignedRiderId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Rider',
      default: null,
    },
    amount: {
      type: Number,
      required: true,
      min: 0,
    },
    paymentMode: {
      type: String,
      enum: ['upi', 'cash', 'prepaid', 'postpaid'],
      default: 'upi',
    },
    paymentStatus: {
      type: String,
      enum: ['pending', 'paid', 'refunded'],
      default: 'pending',
    },
    referralSource: {
      type: referralSourceSubSchema,
      default: () => ({ type: 'none' }),
    },
    idempotencyKey: {
      type: String,
      required: true,
    },
    /**
     * Set only on bookings generated by a recurring subscription cycle.
     *
     * Its presence is what distinguishes "the patient booked this" from "a
     * confirmed AutoPay debit produced this", which matters for refunds and
     * for counting cycles.
     */
    subscriptionId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Subscription',
      default: null,
      index: true,
      sparse: true,
    },
    autoCancelAt: {
      type: Date,
      default: null,
    },
    barcode: {
      type: String,
      trim: true,
      default: null,
    },
    cancelReason: {
      type: String,
      trim: true,
      default: null,
    },
    // Required for mode 'home' — the rider has to know where to go.
    collectionAddress: {
      type: collectionAddressSubSchema,
      default: null,
    },
  },
  {
    timestamps: true,
    collection: 'bookings',
  }
);

// Indexes per PATHCARE_CONTEXT.md §5.3
bookingSchema.index({ patientId: 1, createdAt: -1 });
bookingSchema.index({ labCenterId: 1, status: 1 });
bookingSchema.index({ status: 1, autoCancelAt: 1 });
bookingSchema.index({ idempotencyKey: 1 }, { unique: true, sparse: true });

export const Booking = mongoose.model('Booking', bookingSchema);
export default Booking;
