import React, { useCallback, useRef, useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { CameraView, useCameraPermissions } from 'expo-camera';
import { colors, type } from '../theme.js';
import { GhostButton, PrimaryButton } from './ui.jsx';

/**
 * Camera barcode scanner.
 *
 * Sample barcodes are generated by the server at collection and printed on the
 * vial label; the scanner VERIFIES the label on the tube against the record,
 * it never invents an identifier. That is the difference between confirming you
 * are carrying the right tube and asserting that you are.
 */
const BARCODE_TYPES = ['code128', 'code39', 'ean13', 'qr', 'datamatrix'];

export default function BarcodeScanner({ onScan, expected = null, testID = 'barcode-scanner' }) {
  const [permission, requestPermission] = useCameraPermissions();
  const [lastResult, setLastResult] = useState(null);
  /** The camera fires continuously; without this one tube scans dozens of times. */
  const lockedRef = useRef(false);

  const handleScanned = useCallback(
    ({ data }) => {
      if (lockedRef.current) return;
      lockedRef.current = true;

      const value = String(data || '').trim();
      const matches = expected ? value === String(expected).trim() : true;
      setLastResult({ value, matches });

      if (matches) {
        onScan?.(value);
      } else {
        // Let them try again with the right tube.
        setTimeout(() => {
          lockedRef.current = false;
        }, 1200);
      }
    },
    [expected, onScan]
  );

  if (!permission) {
    return (
      <View style={styles.placeholder} testID={`${testID}-initialising`}>
        <Text style={type.bodyMuted}>Preparing the camera…</Text>
      </View>
    );
  }

  if (!permission.granted) {
    return (
      <View style={styles.placeholder} testID={`${testID}-permission`}>
        <Text style={[type.body, styles.permissionTitle]}>Camera access needed</Text>
        <Text style={[type.bodyMuted, styles.centred]}>
          The camera is used only to read the barcode on the sample vial, so the tube can be checked against this
          collection.
        </Text>
        {permission.canAskAgain ? (
          <PrimaryButton testID="btn-grant-camera" label="Allow camera" onPress={requestPermission} style={styles.action} />
        ) : (
          <Text style={[type.bodyMuted, styles.centred]}>
            Camera access is blocked for this app. Enable it in Settings to scan.
          </Text>
        )}
      </View>
    );
  }

  return (
    <View style={styles.wrap} testID={testID}>
      <View style={styles.cameraFrame}>
        <CameraView
          style={StyleSheet.absoluteFill}
          facing="back"
          barcodeScannerSettings={{ barcodeTypes: BARCODE_TYPES }}
          onBarcodeScanned={handleScanned}
        />
        <View pointerEvents="none" style={styles.reticle} />
      </View>

      {lastResult && !lastResult.matches ? (
        <View style={styles.mismatch} testID="scan-mismatch">
          <Text style={styles.mismatchTitle}>That is a different tube</Text>
          <Text style={styles.mismatchBody}>
            Scanned {lastResult.value}, expected {expected}. Check the label and scan again.
          </Text>
        </View>
      ) : null}

      {lastResult?.matches ? (
        <View style={styles.match} testID="scan-match">
          <Text style={styles.matchText}>Barcode matches · {lastResult.value}</Text>
        </View>
      ) : null}

      <GhostButton
        testID="btn-rescan"
        label="Scan again"
        onPress={() => {
          lockedRef.current = false;
          setLastResult(null);
        }}
        style={styles.action}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  wrap: { gap: 12 },
  cameraFrame: {
    height: 260,
    borderRadius: 20,
    overflow: 'hidden',
    backgroundColor: colors.ink,
    borderWidth: 1,
    borderColor: colors.border,
  },
  reticle: {
    position: 'absolute',
    left: '12%',
    right: '12%',
    top: '28%',
    bottom: '28%',
    borderWidth: 2,
    borderColor: colors.white,
    borderRadius: 14,
    opacity: 0.85,
  },
  placeholder: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 32,
    paddingHorizontal: 20,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.white,
  },
  permissionTitle: { fontWeight: '800' },
  centred: { textAlign: 'center' },
  action: { alignSelf: 'stretch' },
  mismatch: { backgroundColor: colors.redBg, borderRadius: 12, padding: 12, gap: 3 },
  mismatchTitle: { fontSize: 13, fontWeight: '800', color: colors.redDark },
  mismatchBody: { fontSize: 12.5, color: colors.redDark },
  match: { backgroundColor: colors.greenBg, borderRadius: 12, padding: 12 },
  matchText: { fontSize: 13, fontWeight: '800', color: colors.green },
});
