import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { fetchCatalogue, patientKeys } from '@pathcare/api';
import Navbar from '../components/layout/Navbar.jsx';
import Icon from '../components/atoms/Icon.jsx';
import Skeleton from '../components/atoms/Skeleton.jsx';

/**
 * The landing page.
 *
 * There was no `/` route at all — a visitor to the domain matched nothing and
 * got a blank page. This is the first thing anyone sees, so it carries the
 * whole burden of "is this safe to hand my blood to".
 *
 * Structure is informed by how the category leader sells: speed and trust
 * first, concern-led browsing rather than a catalogue dump, and checkup cards
 * that show parameter count and turnaround next to the price so the value is
 * legible without a click.
 *
 * WHAT IS DELIBERATELY NOT COPIED: claims. Competitors lead with "1M+
 * customers", a 4.9 star average and "98% on-time". PathCare has not collected
 * a sample yet, so every one of those would be a fabricated statistic on a
 * medical product — CONTEXT §3.1, and false advertising besides. Every claim
 * below is verifiable on day one: partner accreditation, the turnaround the
 * labs are contracted to, and a collection fee that is genuinely zero. The
 * social-proof slot exists but stays empty until there are real reviews.
 */

const CONCERNS = [
  { key: 'heart', icon: 'heart', label: 'Heart', blurb: 'Lipids, cardiac risk', search: 'lipid' },
  { key: 'diabetes', icon: 'droplet', label: 'Diabetes', blurb: 'Sugar, HbA1c', search: 'diabetes' },
  { key: 'thyroid', icon: 'activity', label: 'Thyroid', blurb: 'TSH, T3, T4', search: 'thyroid' },
  { key: 'liver', icon: 'shield', label: 'Liver', blurb: 'LFT, enzymes', search: 'liver' },
  { key: 'kidney', icon: 'flask', label: 'Kidney', blurb: 'KFT, creatinine', search: 'kidney' },
  { key: 'vitamin', icon: 'star', label: 'Vitamins', blurb: 'D, B12, iron', search: 'vitamin' },
  { key: 'women', icon: 'user', label: "Women's health", blurb: 'Hormones, anaemia', search: 'women' },
  { key: 'fullbody', icon: 'clipboard', label: 'Full body', blurb: 'Annual screening', search: '' },
];

const STEPS = [
  { n: 1, icon: 'search', title: 'Pick your test', body: 'Search by test or by what is worrying you. Compare prices across nearby NABL-accredited labs before you book.' },
  { n: 2, icon: 'calendar', title: 'Choose a slot', body: 'Pick a time that suits you. Home collection is free — a certified phlebotomist comes to your door.' },
  { n: 3, icon: 'snowflake', title: 'Barcode-tracked collection', body: 'Your sample is barcoded at your door and temperature-logged the whole way to the lab.' },
  { n: 4, icon: 'file', title: 'Report in the app', body: 'Get your report with a plain-language summary written by a person at the lab, not generated by an algorithm.' },
];

const FAQS = [
  {
    q: 'How much does home collection cost?',
    a: 'Nothing. A certified phlebotomist comes to your address at no extra charge — you pay only for the test itself.',
  },
  {
    q: 'How is my sample kept safe on the way to the lab?',
    a: 'Every sample is barcoded at the point of collection and its temperature is logged from your door to the lab. You can see each step in the app as it happens.',
  },
  {
    q: 'Which labs process my sample?',
    a: 'Only NABL- or ISO-accredited partner labs in Dehradun. You choose which one before you book, and you can see each lab’s price and turnaround up front.',
  },
  {
    q: 'Do I need to fast?',
    a: 'It depends on the test. Anything requiring fasting says so clearly on its page and in your booking confirmation, with the exact number of hours.',
  },
  {
    q: 'Can I book for a parent or child?',
    a: 'Yes. Add them as a family member and book in their name — every report stays in one account.',
  },
  {
    q: 'Does PathCare take a cut of doctor consultation fees?',
    a: 'No. If a report suggests seeing a specialist, you pay that doctor directly at their clinic. PathCare charges no booking fee and takes no share of the consultation.',
  },
];

function formatPrice(value) {
  if (value === null || value === undefined) return '—';
  return `₹${Number(value).toLocaleString('en-IN')}`;
}

export default function HomePage() {
  const navigate = useNavigate();
  const [search, setSearch] = useState('');
  const [openFaq, setOpenFaq] = useState(0);

  // Real catalogue, not hardcoded cards. An empty or failed load degrades to
  // skeletons and then to nothing rather than to invented products.
  const packagesQuery = useQuery({
    queryKey: patientKeys.catalogue({ category: 'package' }),
    queryFn: () => fetchCatalogue({ category: 'package' }),
  });
  const popularQuery = useQuery({
    queryKey: patientKeys.catalogue({ category: 'single' }),
    queryFn: () => fetchCatalogue({ category: 'single', limit: 6 }),
  });

  const packages = packagesQuery.data?.items ?? [];
  const popular = (popularQuery.data?.items ?? []).slice(0, 6);

  function submitSearch(event) {
    event.preventDefault();
    navigate(search.trim() ? `/tests?q=${encodeURIComponent(search.trim())}` : '/tests');
  }

  return (
    <div className="min-h-screen bg-bg">
      <Navbar />

      {/* ── HERO ─────────────────────────────────────────────────────────── */}
      <section className="relative overflow-hidden bg-blue900">
        {/* Depth without imagery: two soft radial washes over the deep blue. */}
        <div
          aria-hidden="true"
          className="pointer-events-none absolute -top-40 -left-32 h-[520px] w-[520px] rounded-full opacity-40 blur-3xl"
          style={{ background: 'radial-gradient(circle, #4F72E8 0%, transparent 70%)' }}
        />
        <div
          aria-hidden="true"
          className="pointer-events-none absolute -bottom-52 right-0 h-[460px] w-[460px] rounded-full opacity-30 blur-3xl"
          style={{ background: 'radial-gradient(circle, #7C93EE 0%, transparent 70%)' }}
        />

        <div className="relative mx-auto max-w-[1240px] px-7 pt-16 pb-20 md:pt-24 md:pb-28">
          <div className="grid items-center gap-12 md:grid-cols-[1.05fr_0.95fr]">
            <div>
              <span className="inline-flex items-center gap-2 rounded-pill bg-white/10 px-3.5 py-1.5 text-caption font-bold uppercase tracking-[0.06em] text-white/90 backdrop-blur">
                <Icon name="mapPin" size={13} strokeWidth={2.4} />
                Now live in Dehradun
              </span>

              <h1 className="mt-6 text-[38px] font-extrabold leading-[1.06] tracking-[-0.02em] text-white md:text-[52px]">
                Lab tests at home,
                <br />
                <span className="text-blue500">reports the same day.</span>
              </h1>

              <p className="mt-5 max-w-[520px] text-body leading-relaxed text-white/75">
                A certified phlebotomist collects your sample at home, free. It travels
                barcoded and temperature-tracked to a NABL-accredited lab — and you watch
                every step from your phone.
              </p>

              {/* The search bar is the primary action: most people arrive with a
                  test name or a symptom in mind, not a desire to browse. */}
              <form onSubmit={submitSearch} className="mt-8 max-w-[540px]">
                <div className="flex flex-col gap-3 sm:flex-row">
                  <div className="relative flex-1">
                    <Icon
                      name="search"
                      size={18}
                      className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-muted2"
                    />
                    <input
                      type="text"
                      value={search}
                      onChange={(e) => setSearch(e.target.value)}
                      placeholder="Search a test, or how you're feeling…"
                      aria-label="Search tests"
                      data-testid="home-search"
                      className="w-full rounded-pill border-none bg-white py-4 pl-12 pr-4 text-body text-ink outline-none placeholder:text-muted2 focus:ring-4 focus:ring-blue500/40"
                    />
                  </div>
                  <button
                    type="submit"
                    data-testid="home-search-submit"
                    className="rounded-pill bg-blue600 px-7 py-4 text-body font-bold text-white transition hover:bg-blue700"
                  >
                    Find tests
                  </button>
                </div>
              </form>

              {/* Claims true on day one. No invented counts. */}
              <div className="mt-9 flex flex-wrap gap-x-8 gap-y-4">
                {[
                  { icon: 'shield', big: 'NABL & ISO', small: 'Accredited partner labs' },
                  { icon: 'clock', big: '6 hours', small: 'Typical turnaround' },
                  { icon: 'rupee', big: '₹0', small: 'Home collection fee' },
                ].map((claim) => (
                  <div key={claim.big} className="flex items-center gap-3">
                    <span className="flex h-10 w-10 items-center justify-center rounded-lg bg-white/10 text-white backdrop-blur">
                      <Icon name={claim.icon} size={18} strokeWidth={2.2} />
                    </span>
                    <span>
                      <span className="block text-cardTitle font-extrabold text-white">{claim.big}</span>
                      <span className="block text-caption text-white/60">{claim.small}</span>
                    </span>
                  </div>
                ))}
              </div>
            </div>

            {/* Right column: the promise, stated as a timeline. */}
            <div className="relative hidden md:block">
              <div className="overflow-hidden rounded-2xl border border-white/10 bg-white/[0.07] backdrop-blur-sm">
                {/* Illustrative photography, not a photo of our own staff or
                    labs — see public/img/CREDITS.md. It sets the scene without
                    claiming to depict anything specific, which is why the
                    caption describes the service and not the picture. */}
                <div className="relative h-[180px]">
                  <img
                    src="/img/collection-home.jpg"
                    alt="A gloved phlebotomist drawing blood from a patient's arm"
                    loading="eager"
                    className="h-full w-full object-cover"
                  />
                  <div
                    aria-hidden="true"
                    className="absolute inset-0"
                    style={{
                      background:
                        'linear-gradient(180deg, rgba(16,22,53,0.15) 0%, rgba(16,22,53,0.92) 100%)',
                    }}
                  />
                </div>

                <div className="p-7 pt-6">
                <p className="text-caption font-bold uppercase tracking-[0.06em] text-white/60">
                  What happens after you book
                </p>
                <ol className="mt-6 space-y-6">
                  {[
                    { icon: 'user', t: 'A phlebotomist is assigned', s: 'You see who is coming, and when' },
                    { icon: 'mapPin', t: 'Track them to your door', s: 'Live location while they are en route' },
                    { icon: 'snowflake', t: 'Barcoded and cold-chained', s: 'Temperature logged to the lab' },
                    { icon: 'file', t: 'Report with a written summary', s: 'In plain language, by a real person' },
                  ].map((row, i, arr) => (
                    <li key={row.t} className="relative flex gap-4">
                      {i < arr.length - 1 && (
                        <span aria-hidden="true" className="absolute left-[19px] top-11 h-[calc(100%-8px)] w-px bg-white/15" />
                      )}
                      <span className="relative z-10 flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-blue600 text-white">
                        <Icon name={row.icon} size={17} strokeWidth={2.2} />
                      </span>
                      <span className="pt-1">
                        <span className="block text-bodySmall font-bold text-white">{row.t}</span>
                        <span className="block text-caption text-white/55">{row.s}</span>
                      </span>
                    </li>
                  ))}
                </ol>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── BROWSE BY CONCERN ────────────────────────────────────────────── */}
      <section className="mx-auto max-w-[1240px] px-7 py-16 md:py-20">
        <h2 className="text-sectionTitle font-extrabold tracking-[-0.02em] text-ink">
          What are you checking?
        </h2>
        <p className="mt-2 text-bodySmall text-muted">
          Start from a concern rather than a test name — we will show you what is relevant.
        </p>

        <div className="mt-8 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4">
          {CONCERNS.map((c) => (
            <button
              key={c.key}
              type="button"
              data-testid={`concern-${c.key}`}
              onClick={() => navigate(c.search ? `/tests?q=${c.search}` : '/tests')}
              className="group flex items-start gap-3.5 rounded-xl border border-border bg-white p-5 text-left transition hover:-translate-y-0.5 hover:border-blue600 hover:shadow-card"
            >
              <span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-lg bg-blue50 text-blue700 transition group-hover:bg-blue100">
                <Icon name={c.icon} size={20} strokeWidth={2} />
              </span>
              <span className="min-w-0">
                <span className="block text-bodySmall font-extrabold text-ink">{c.label}</span>
                <span className="mt-0.5 block text-caption text-muted">{c.blurb}</span>
              </span>
            </button>
          ))}
        </div>
      </section>

      {/* ── FULL BODY CHECKUPS ───────────────────────────────────────────── */}
      <section className="bg-white py-16 md:py-20">
        <div className="mx-auto max-w-[1240px] px-7">
          <div className="flex flex-wrap items-end justify-between gap-4">
            <div>
              <h2 className="text-sectionTitle font-extrabold tracking-[-0.02em] text-ink">
                Full body checkups
              </h2>
              <p className="mt-2 text-bodySmall text-muted">
                One collection, dozens of parameters. Prices shown are the lowest across our
                partner labs.
              </p>
            </div>
            <button
              type="button"
              onClick={() => navigate('/tests')}
              className="rounded-pill border-[1.5px] border-border px-5 py-2.5 text-bodySmall font-bold text-ink transition hover:border-blue600 hover:text-blue600"
            >
              View all
            </button>
          </div>

          <div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">
            {packagesQuery.isLoading &&
              [0, 1].map((i) => <Skeleton key={i} className="h-[220px] w-full rounded-xl" />)}

            {packages.map((pkg) => {
              const discounted = pkg.strikePrice && pkg.strikePrice > pkg.basePrice;
              const off = discounted
                ? Math.round(((pkg.strikePrice - pkg.basePrice) / pkg.strikePrice) * 100)
                : 0;
              return (
                <button
                  key={pkg.slug}
                  type="button"
                  data-testid={`home-package-${pkg.slug}`}
                  onClick={() => navigate(`/tests/${pkg.slug}`)}
                  className="group relative flex flex-col rounded-xl border border-border bg-white p-6 text-left transition hover:-translate-y-1 hover:border-blue600 hover:shadow-card"
                >
                  {discounted && (
                    <span className="absolute right-5 top-5 rounded-pill bg-redBg px-2.5 py-1 text-[11px] font-extrabold text-redDark">
                      {off}% OFF
                    </span>
                  )}

                  <span className="pr-20 text-cardTitle font-extrabold leading-snug text-ink">
                    {pkg.name}
                  </span>

                  <span className="mt-3 flex flex-wrap gap-x-4 gap-y-1.5 text-caption text-muted">
                    {pkg.parametersCount > 0 && (
                      <span className="inline-flex items-center gap-1.5">
                        <Icon name="clipboard" size={13} strokeWidth={2.2} />
                        {pkg.parametersCount} parameters
                      </span>
                    )}
                    <span className="inline-flex items-center gap-1.5">
                      <Icon name="clock" size={13} strokeWidth={2.2} />
                      Reports in {pkg.turnaroundHrs} hrs
                    </span>
                  </span>

                  <span className="mt-4 line-clamp-2 text-bodySmall leading-relaxed text-muted">
                    {pkg.description}
                  </span>

                  <span className="mt-5 flex items-baseline gap-2.5 border-t border-border pt-4">
                    <span className="text-price font-extrabold text-ink">
                      {formatPrice(pkg.basePrice)}
                    </span>
                    {discounted && (
                      <span className="text-caption text-muted2 line-through">
                        {formatPrice(pkg.strikePrice)}
                      </span>
                    )}
                    <span className="ml-auto inline-flex items-center gap-1 text-bodySmall font-bold text-blue600">
                      Book
                      <Icon name="chevronRight" size={15} strokeWidth={2.4} />
                    </span>
                  </span>
                </button>
              );
            })}
          </div>
        </div>
      </section>

      {/* ── HOW IT WORKS ─────────────────────────────────────────────────── */}
      <section className="mx-auto max-w-[1240px] px-7 py-16 md:py-20">
        <h2 className="text-sectionTitle font-extrabold tracking-[-0.02em] text-ink">
          How it works
        </h2>

        <div className="mt-10 grid gap-10 lg:grid-cols-[1fr_0.8fr] lg:items-start">
          <div className="grid gap-8 sm:grid-cols-2">
            {STEPS.map((step) => (
              <div key={step.n} className="relative">
                <span className="flex h-12 w-12 items-center justify-center rounded-lg bg-blue600 text-white">
                  <Icon name={step.icon} size={21} strokeWidth={2.1} />
                </span>
                <span className="mt-5 block text-caption font-extrabold uppercase tracking-[0.06em] text-blue600">
                  Step {step.n}
                </span>
                <h3 className="mt-1.5 text-cardTitle font-extrabold text-ink">{step.title}</h3>
                <p className="mt-2 text-bodySmall leading-relaxed text-muted">{step.body}</p>
              </div>
            ))}
          </div>

          {/* A page about drawing blood that shows no blood being drawn reads
              as a brochure. Both images are illustrative (CREDITS.md) and are
              captioned with what we do, never with a claim about the picture. */}
          <div className="hidden gap-4 lg:grid">
            <figure className="overflow-hidden rounded-2xl border border-border bg-white">
              <img
                src="/img/phlebotomist.jpg"
                alt="A masked healthcare worker holding a blood sample tube beside a rack of colour-coded tubes"
                loading="lazy"
                className="h-[240px] w-full object-cover"
              />
              <figcaption className="px-5 py-4 text-caption leading-relaxed text-muted">
                Collections are done by certified phlebotomists whose training records we
                hold on file.
              </figcaption>
            </figure>
            <figure className="overflow-hidden rounded-2xl border border-border bg-white">
              <img
                src="/img/lab-tech.jpg"
                alt="A laboratory technician in a cap, mask and gloves working with samples at a bench"
                loading="lazy"
                className="h-[200px] w-full object-cover"
              />
              <figcaption className="px-5 py-4 text-caption leading-relaxed text-muted">
                Processing happens at NABL or ISO accredited partner labs — we verify the
                accreditation and track when it expires.
              </figcaption>
            </figure>
          </div>
        </div>
      </section>

      {/* ── POPULAR TESTS ────────────────────────────────────────────────── */}
      {popular.length > 0 && (
        <section className="bg-white py-16 md:py-20">
          <div className="mx-auto max-w-[1240px] px-7">
            <h2 className="text-sectionTitle font-extrabold tracking-[-0.02em] text-ink">
              Individual tests
            </h2>
            <p className="mt-2 text-bodySmall text-muted">
              Booked on their own, or added to a checkup.
            </p>

            <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
              {popular.map((test) => (
                <button
                  key={test.slug}
                  type="button"
                  data-testid={`home-test-${test.slug}`}
                  onClick={() => navigate(`/tests/${test.slug}`)}
                  className="flex items-center justify-between gap-4 rounded-xl border border-border bg-white px-5 py-4 text-left transition hover:border-blue600 hover:shadow-card"
                >
                  <span className="min-w-0">
                    <span className="block truncate text-bodySmall font-extrabold text-ink">
                      {test.name}
                    </span>
                    <span className="mt-1 flex items-center gap-1.5 text-caption text-muted">
                      <Icon name="clock" size={12} strokeWidth={2.2} />
                      {test.turnaroundHrs} hrs
                      {test.homeCollectionAvailable === false && (
                        <span className="ml-1 text-amberDark">· lab visit only</span>
                      )}
                    </span>
                  </span>
                  <span className="shrink-0 text-cardTitle font-extrabold text-ink">
                    {formatPrice(test.basePrice)}
                  </span>
                </button>
              ))}
            </div>
          </div>
        </section>
      )}

      {/* ── WHY TRUST US ─────────────────────────────────────────────────── */}
      <section className="mx-auto max-w-[1240px] px-7 py-16 md:py-20">
        <div className="rounded-2xl bg-blue900 p-8 md:p-14">
          <h2 className="max-w-[620px] text-sectionTitle font-extrabold tracking-[-0.02em] text-white">
            Why a sample you can follow matters
          </h2>
          <p className="mt-3 max-w-[620px] text-bodySmall leading-relaxed text-white/70">
            A blood test is only as good as the handling between your arm and the analyser.
            Most of that is invisible to you. We made it visible.
          </p>

          <div className="mt-10 grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
            {[
              { icon: 'snowflake', t: 'Temperature logged end to end', b: 'Every reading recorded from your door to the lab bench, with the time it was taken.' },
              { icon: 'shield', t: 'Barcoded at your door', b: 'Your sample is labelled in front of you and scanned again at handoff, so it cannot be mixed up.' },
              { icon: 'user', t: 'Trained phlebotomists', b: 'Certified collectors, with their training date on record before they take a single sample.' },
              { icon: 'microscope', t: 'Accredited labs only', b: 'NABL or ISO accreditation verified, with expiry tracked — not taken on trust.' },
              { icon: 'file', t: 'Summaries written by people', b: 'A qualified person at the lab reads your report and writes the summary. No algorithm interprets your results.' },
              { icon: 'rupee', t: 'The price you were quoted', b: 'Confirmed against the live catalogue at checkout. No surprise additions.' },
            ].map((item) => (
              <div key={item.t}>
                <span className="flex h-11 w-11 items-center justify-center rounded-lg bg-white/10 text-white">
                  <Icon name={item.icon} size={19} strokeWidth={2.1} />
                </span>
                <h3 className="mt-4 text-cardTitle font-extrabold text-white">{item.t}</h3>
                <p className="mt-1.5 text-bodySmall leading-relaxed text-white/65">{item.b}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── AFTER THE REPORT ─────────────────────────────────────────────── */}
      {/* The gap competitors fill and we did not show anywhere: a result is not
          the end of the job. Everything claimed here is a feature that exists —
          lab-written summaries, and the partner-doctor directory where the fee
          is paid to the clinic and PathCare takes no share (CONTEXT §2.2). */}
      <section className="bg-white py-16 md:py-20">
        <div className="mx-auto max-w-[1240px] px-7">
          <div className="grid items-center gap-12 lg:grid-cols-2">
            <figure className="order-2 overflow-hidden rounded-2xl lg:order-1">
              <img
                src="/img/report-review.jpg"
                alt="A doctor talking a patient through their results across a desk"
                loading="lazy"
                className="h-[300px] w-full object-cover md:h-[380px]"
              />
            </figure>

            <div className="order-1 lg:order-2">
              <span className="text-caption font-extrabold uppercase tracking-[0.06em] text-blue600">
                After your report
              </span>
              <h2 className="mt-2 text-sectionTitle font-extrabold tracking-[-0.02em] text-ink">
                A number on a page is not an answer
              </h2>
              <p className="mt-4 text-bodySmall leading-relaxed text-muted">
                Every report we deliver carries a written summary from a qualified person at
                the processing lab — in plain language, not an automated interpretation. If
                you want to take it further, you can book a consultation with a partner
                doctor from the same account.
              </p>

              <ul className="mt-7 space-y-4">
                {[
                  {
                    icon: 'file',
                    t: 'A summary written by a person',
                    b: 'Someone qualified reads your results and explains what they mean. No algorithm interprets your report.',
                  },
                  {
                    icon: 'stethoscope',
                    t: 'Consult a partner doctor',
                    b: 'You pay the doctor directly at their clinic. PathCare charges no booking fee and takes no share of the consultation.',
                  },
                  {
                    icon: 'inbox',
                    t: 'Sent to your referring doctor',
                    b: 'If a doctor referred you, the report reaches them at no extra charge.',
                  },
                ].map((row) => (
                  <li key={row.t} className="flex gap-4">
                    <span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-blue50 text-blue600">
                      <Icon name={row.icon} size={18} strokeWidth={2.1} />
                    </span>
                    <span>
                      <span className="block text-bodySmall font-extrabold text-ink">{row.t}</span>
                      <span className="mt-1 block text-caption leading-relaxed text-muted">
                        {row.b}
                      </span>
                    </span>
                  </li>
                ))}
              </ul>

              <button
                type="button"
                data-testid="home-find-doctor"
                onClick={() => navigate('/doctors')}
                className="mt-8 inline-flex items-center gap-2 rounded-pill border-[1.5px] border-blue600 px-7 py-3 text-body font-bold text-blue600 transition hover:bg-blue600 hover:text-white"
              >
                <Icon name="stethoscope" size={17} strokeWidth={2.1} />
                Find a doctor
              </button>
            </div>
          </div>
        </div>
      </section>

      {/* ── FAQ ──────────────────────────────────────────────────────────── */}
      <section className="mx-auto max-w-[820px] px-7 pb-20">
        <h2 className="text-sectionTitle font-extrabold tracking-[-0.02em] text-ink">
          Questions people ask
        </h2>

        <div className="mt-8 divide-y divide-border overflow-hidden rounded-xl border border-border bg-white">
          {FAQS.map((faq, i) => {
            const open = openFaq === i;
            return (
              <div key={faq.q}>
                <button
                  type="button"
                  data-testid={`faq-${i}`}
                  aria-expanded={open}
                  onClick={() => setOpenFaq(open ? -1 : i)}
                  className="flex w-full items-center justify-between gap-4 px-6 py-5 text-left transition hover:bg-blue50"
                >
                  <span className="text-bodySmall font-extrabold text-ink">{faq.q}</span>
                  <span className={`shrink-0 text-blue600 transition-transform ${open ? 'rotate-45' : ''}`}>
                    <Icon name="plus" size={18} strokeWidth={2.4} />
                  </span>
                </button>
                {open && (
                  <p
                    data-testid={`faq-answer-${i}`}
                    className="px-6 pb-5 text-bodySmall leading-relaxed text-muted"
                  >
                    {faq.a}
                  </p>
                )}
              </div>
            );
          })}
        </div>
      </section>

      {/* ── CLOSING CTA ──────────────────────────────────────────────────── */}
      {/* Two audiences arrive on this page — patients, and the labs and doctors
          we need in order to serve them. Both get a door out. */}
      <section className="border-t border-border bg-white py-16">
        <div className="mx-auto grid max-w-[1240px] gap-6 px-7 lg:grid-cols-2">
          {[
            {
              key: 'patient',
              img: '/img/hero-lab.jpg',
              alt: 'A gloved lab worker loading a blood sample tube into a centrifuge',
              eyebrow: 'For patients',
              title: 'Book a test in under a minute',
              body: 'Free home collection across Dehradun. Choose your lab, choose your slot.',
              cta: 'Browse tests',
              testid: 'home-cta-browse',
              to: '/tests',
            },
            {
              key: 'partner',
              img: '/img/care-doctor.jpg',
              alt: 'A doctor in a white coat writing notes across a desk from a patient',
              eyebrow: 'For labs and doctors',
              title: 'Partner with PathCare',
              body: 'Accredited labs receive bookings from patients nearby. Doctors receive their patients’ reports at no charge, and we pay no referral commissions.',
              cta: 'Partner with us',
              testid: 'home-cta-partner',
              to: '/partner',
            },
          ].map((card) => (
            <div
              key={card.key}
              className="relative overflow-hidden rounded-2xl bg-blue900 min-h-[300px] flex"
            >
              <img
                src={card.img}
                alt={card.alt}
                loading="lazy"
                className="absolute inset-0 h-full w-full object-cover"
              />
              {/* Text over a photo is unreadable without this, and "unreadable"
                  on a dark-on-dark day is a real accessibility failure. */}
              <div
                aria-hidden="true"
                className="absolute inset-0"
                style={{
                  background:
                    'linear-gradient(105deg, rgba(16,22,53,0.94) 0%, rgba(16,22,53,0.86) 45%, rgba(16,22,53,0.55) 100%)',
                }}
              />
              <div className="relative flex flex-col justify-end p-8 md:p-10">
                <span className="text-caption font-extrabold uppercase tracking-[0.06em] text-blue500">
                  {card.eyebrow}
                </span>
                <h2 className="mt-2 max-w-[380px] text-[26px] font-extrabold leading-tight tracking-[-0.02em] text-white">
                  {card.title}
                </h2>
                <p className="mt-3 max-w-[420px] text-bodySmall leading-relaxed text-white/70">
                  {card.body}
                </p>
                <div>
                  <button
                    type="button"
                    data-testid={card.testid}
                    onClick={() => navigate(card.to)}
                    className="mt-6 rounded-pill bg-white px-7 py-3 text-body font-bold text-ink transition hover:bg-blue600 hover:text-white"
                  >
                    {card.cta}
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* ── FOOTER ───────────────────────────────────────────────────────── */}
      <footer className="bg-dark py-14">
        <div className="mx-auto max-w-[1240px] px-7">
          <div className="grid gap-10 sm:grid-cols-2 lg:grid-cols-4">
            <div>
              <span className="flex items-center gap-2 text-lg font-extrabold text-white">
                <Icon name="check" size={20} className="text-blue500" strokeWidth={2.6} />
                Path<span className="font-extrabold text-white/70">Care</span>
              </span>
              <p className="mt-3 max-w-[240px] text-caption leading-relaxed text-white/50">
                On-demand pathology and diagnostics. Dehradun, Uttarakhand.
              </p>
            </div>

            {[
              { h: 'Book', links: [['Tests & packages', '/tests'], ['Find a doctor', '/doctors'], ['Track an order', '/track']] },
              { h: 'Company', links: [['About us', '/about'], ['Partner with us', '/partner']] },
              { h: 'Account', links: [['Sign in', '/auth'], ['My profile', '/profile']] },
            ].map((col) => (
              <div key={col.h}>
                <span className="text-caption font-extrabold uppercase tracking-[0.06em] text-white/40">
                  {col.h}
                </span>
                <ul className="mt-4 space-y-2.5">
                  {col.links.map(([label, href]) => (
                    <li key={label}>
                      <button
                        type="button"
                        onClick={() => navigate(href)}
                        className="text-bodySmall text-white/70 transition hover:text-white"
                      >
                        {label}
                      </button>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>

          <div className="mt-12 border-t border-white/10 pt-6 text-caption text-white/40">
            Partner labs are NABL or ISO accredited. Reports are issued by the processing
            laboratory.
          </div>
        </div>
      </footer>
    </div>
  );
}
