// common/catalogData.js — Catalogue data shared across web, mobile & backend.
//
// SCOPE OF THIS FILE (CONTEXT §3.1, §11):
//   The TEST CATALOGUE below (names, prices, parameters, prep instructions) is
//   legitimate business data and is safe to seed.
//
//   The LAB CENTRES are DEVELOPMENT FIXTURES. They previously carried invented
//   contact phone numbers and invented NABL/ISO/ICMR accreditation with expiry
//   dates -- regulatory assertions about real-world entities that nobody had
//   verified. Those have been removed. Accreditation and contact details must
//   be entered per centre through the admin panel from real paperwork; they are
//   deliberately absent here so an unverified centre cannot masquerade as an
//   accredited one.
//
//   Partner DOCTORS are not seeded at all -- see seedCatalogue.js.
export const REAL_TESTS = [
  // 12 SINGLE TESTS
  {
    name: 'Complete Blood Count (CBC)',
    slug: 'complete-blood-count-cbc',
    category: 'single',
    sampleType: 'Blood',
    homeCollectionAvailable: true,
    basePrice: 299,
    turnaroundHrs: 6,
    parametersCount: 24,
    parameters: [
      'Hemoglobin',
      'RBC Count',
      'WBC Count',
      'Platelet Count',
      'Hematocrit',
      'MCV',
      'MCH',
      'MCHC',
      'Neutrophils',
      'Lymphocytes',
      'Monocytes',
      'Eosinophils',
      'Basophils',
    ],
    prepInstructions: 'No fasting required.',
    description:
      'Measures red cells, white cells, haemoglobin and platelets — the standard first-line screen for infection, anaemia and inflammation.',
    isPopular: true,
    tags: ['fever', 'infection', 'anaemia', 'routine'],
  },
  {
    name: 'Lipid Profile',
    slug: 'lipid-profile',
    category: 'single',
    sampleType: 'Blood',
    homeCollectionAvailable: true,
    basePrice: 499,
    turnaroundHrs: 6,
    parametersCount: 10,
    parameters: [
      'Total Cholesterol',
      'Triglycerides',
      'HDL Cholesterol',
      'LDL Cholesterol',
      'VLDL Cholesterol',
      'Chol/HDL Ratio',
    ],
    prepInstructions: '12-hour fasting required. Water is fine.',
    description:
      'Total cholesterol, HDL, LDL and triglycerides — used to assess cardiovascular risk and heart health.',
    isPopular: true,
    tags: ['heart', 'cholesterol', 'cardiac', 'fasting'],
  },
  {
    name: 'Thyroid Profile (TSH, T3, T4)',
    slug: 'thyroid-profile-tsh-t3-t4',
    category: 'single',
    sampleType: 'Blood',
    homeCollectionAvailable: true,
    basePrice: 449,
    turnaroundHrs: 12,
    parametersCount: 3,
    parameters: ['Total T3', 'Total T4', 'TSH (Ultrasensitive)'],
    prepInstructions: 'No fasting required. Morning sample preferred.',
    description:
      'Screens thyroid gland function for hypo- and hyperthyroidism, weight fluctuations, and metabolic balance.',
    isPopular: true,
    tags: ['thyroid', 'hormones', 'weight', 'metabolism'],
  },
  {
    name: 'HbA1c (3-Month Sugar Average)',
    slug: 'hba1c-glycated-hemoglobin',
    category: 'single',
    sampleType: 'Blood',
    homeCollectionAvailable: true,
    basePrice: 399,
    turnaroundHrs: 6,
    parametersCount: 1,
    parameters: ['Glycated Hemoglobin (HbA1c)', 'Average Estimated Glucose (eAG)'],
    prepInstructions: 'No fasting required.',
    description:
      'Reflects average blood glucose over roughly three months — the clinical gold standard for diabetes monitoring.',
    isPopular: true,
    tags: ['diabetes', 'sugar', 'glucose'],
  },
  {
    name: 'Liver Function Test (LFT)',
    slug: 'liver-function-test-lft',
    category: 'single',
    sampleType: 'Blood',
    homeCollectionAvailable: true,
    basePrice: 599,
    turnaroundHrs: 8,
    parametersCount: 12,
    parameters: [
      'Bilirubin Total',
      'Bilirubin Direct',
      'SGOT / AST',
      'SGPT / ALT',
      'Alkaline Phosphatase',
      'Total Protein',
      'Albumin',
      'Globulin',
      'A/G Ratio',
    ],
    prepInstructions: '8-hour fasting recommended.',
    description:
      'Assesses liver enzymes, bilirubin and cellular proteins to evaluate hepatic function and detoxification.',
    isPopular: false,
    tags: ['liver', 'enzymes', 'jaundice'],
  },
  {
    name: 'Kidney Function Test (KFT)',
    slug: 'kidney-function-test-kft',
    category: 'single',
    sampleType: 'Blood',
    homeCollectionAvailable: true,
    basePrice: 549,
    turnaroundHrs: 8,
    parametersCount: 10,
    parameters: [
      'Serum Creatinine',
      'Blood Urea',
      'BUN',
      'Uric Acid',
      'eGFR',
      'Calcium',
      'Phosphorus',
    ],
    prepInstructions: 'No fasting required. Stay well hydrated.',
    description:
      'Measures creatinine, urea and renal filtration markers to detect early kidney disease and filtration efficiency.',
    isPopular: false,
    tags: ['kidney', 'creatinine', 'renal'],
  },
  {
    name: 'Urine Routine & Microscopy',
    slug: 'urine-routine-microscopy',
    category: 'single',
    sampleType: 'Urine',
    homeCollectionAvailable: true,
    basePrice: 199,
    turnaroundHrs: 4,
    parametersCount: 14,
    parameters: [
      'Color',
      'pH',
      'Specific Gravity',
      'Protein',
      'Glucose',
      'Ketones',
      'Pus Cells',
      'RBCs',
      'Epithelial Cells',
      'Crystals',
      'Bacteria',
    ],
    prepInstructions: 'First-morning midstream sample preferred.',
    description:
      'Screens for urinary tract infection, kidney issues, metabolic markers, and hydration balance.',
    isPopular: true,
    tags: ['urine', 'uti', 'infection'],
  },
  {
    name: 'Vitamin D (25-OH)',
    slug: 'vitamin-d-25-oh',
    category: 'single',
    sampleType: 'Blood',
    homeCollectionAvailable: true,
    basePrice: 899,
    turnaroundHrs: 24,
    parametersCount: 1,
    parameters: ['25-Hydroxy Vitamin D Total'],
    prepInstructions: 'No fasting required.',
    description:
      'Measures circulating vitamin D sufficiency — critical for bone density, immunity, and energy.',
    isPopular: true,
    tags: ['vitamin', 'bones', 'immunity'],
  },
  {
    name: 'Vitamin B12 (Cyanocobalamin)',
    slug: 'vitamin-b12-cyanocobalamin',
    category: 'single',
    sampleType: 'Blood',
    homeCollectionAvailable: true,
    basePrice: 699,
    turnaroundHrs: 12,
    parametersCount: 1,
    parameters: ['Vitamin B12 Serum'],
    prepInstructions: 'Overnight fasting recommended.',
    description:
      'Evaluates vitamin B12 levels essential for neurological health, cognitive function, and red blood cell production.',
    isPopular: false,
    tags: ['vitamin', 'nerve', 'fatigue'],
  },
  {
    name: 'Serum Ferritin',
    slug: 'serum-ferritin',
    category: 'single',
    sampleType: 'Blood',
    homeCollectionAvailable: true,
    basePrice: 499,
    turnaroundHrs: 8,
    parametersCount: 1,
    parameters: ['Serum Ferritin'],
    prepInstructions: '12-hour fasting required.',
    description:
      'Measures iron storage capacity to investigate fatigue, chronic blood loss, or iron-deficiency anaemia.',
    isPopular: false,
    tags: ['iron', 'anaemia', 'fatigue'],
  },
  {
    name: 'Fasting Blood Glucose (FBS)',
    slug: 'fasting-blood-glucose',
    category: 'single',
    sampleType: 'Blood',
    homeCollectionAvailable: true,
    basePrice: 149,
    turnaroundHrs: 4,
    parametersCount: 1,
    parameters: ['Fasting Blood Sugar'],
    prepInstructions: '8 to 10 hours strict overnight fasting mandatory.',
    description: 'Primary diagnostic test for diagnosing prediabetes and diabetes mellitus.',
    isPopular: false,
    tags: ['sugar', 'diabetes', 'glucose', 'fasting'],
  },
  {
    name: 'Electrolytes Serum (Na/K/Cl)',
    slug: 'serum-electrolytes',
    category: 'single',
    sampleType: 'Blood',
    homeCollectionAvailable: true,
    basePrice: 399,
    turnaroundHrs: 6,
    parametersCount: 3,
    parameters: ['Sodium', 'Potassium', 'Chloride'],
    prepInstructions: 'No fasting required.',
    description:
      'Monitors vital electrolyte and mineral equilibrium regulating cellular fluid volume and cardiac rhythm.',
    isPopular: false,
    tags: ['electrolytes', 'potassium', 'hydration'],
  },

  // 2 FULL BODY PACKAGES
  {
    name: 'Full Body Checkup — Essential',
    slug: 'full-body-checkup-essential',
    category: 'package',
    sampleType: 'Blood',
    homeCollectionAvailable: true,
    basePrice: 1499,
    strikePrice: 1999,
    turnaroundHrs: 8,
    parametersCount: 54,
    parameters: [
      'CBC (24)',
      'Lipid Profile (10)',
      'Liver Function (12)',
      'Kidney Function (10)',
      'Fasting Sugar (1)',
      'Thyroid TSH (1)',
    ],
    prepInstructions: '12-hour fasting required.',
    description:
      'A 54-parameter baseline covering blood count, sugar, lipids, liver, kidney and thyroid — the recommended annual screen for healthy adults.',
    isPopular: true,
    tags: ['full body', 'annual checkup', 'preventive'],
  },
  {
    name: 'Full Body Checkup — Comprehensive',
    slug: 'full-body-checkup-comprehensive',
    category: 'package',
    sampleType: 'Blood',
    homeCollectionAvailable: true,
    basePrice: 3499,
    strikePrice: 4999,
    turnaroundHrs: 10,
    parametersCount: 90,
    parameters: [
      'CBC (24)',
      'Lipid Profile (10)',
      'Liver Function (12)',
      'Kidney Function (10)',
      'Complete Thyroid Profile (3)',
      'Vitamin D & B12 (2)',
      'Iron Studies (4)',
      'HbA1c (1)',
      'Urine Routine (14)',
      'Cardiac Risk Factors',
    ],
    prepInstructions: '12-hour fasting required.',
    description:
      'A 90-parameter panel adding vitamins, iron studies, electrolytes and a full urine screen. Includes a written lab summary with your report.',
    isPopular: true,
    tags: ['full body', 'executive', 'vitamins', 'comprehensive'],
  },

  // 3 IMAGING TESTS (CRITICAL: homeCollectionAvailable = false)
  {
    name: 'Ultrasound — Whole Abdomen',
    slug: 'ultrasound-whole-abdomen',
    category: 'imaging',
    sampleType: 'Imaging',
    homeCollectionAvailable: false,
    basePrice: 1200,
    turnaroundHrs: 4,
    parametersCount: 0,
    parameters: ['Liver', 'Gallbladder', 'Spleen', 'Pancreas', 'Kidneys', 'Urinary Bladder'],
    prepInstructions: '6-hour fasting. Drink 1L water and hold a full bladder.',
    description:
      'Ultrasound imaging of the abdominal organs. Performed at the lab centre — home collection is not available for imaging.',
    isPopular: false,
    tags: ['imaging', 'scan', 'ultrasound', 'abdomen'],
  },
  {
    name: 'Digital X-Ray — Chest PA',
    slug: 'digital-x-ray-chest-pa',
    category: 'imaging',
    sampleType: 'Imaging',
    homeCollectionAvailable: false,
    basePrice: 450,
    turnaroundHrs: 2,
    parametersCount: 0,
    parameters: ['Lung Fields', 'Cardiac Silhouette', 'Bony Thorax', 'Diaphragm'],
    prepInstructions: 'Remove metal jewellery and upper garments before the scan.',
    description: 'Standard chest radiograph. Performed at the lab centre.',
    isPopular: false,
    tags: ['imaging', 'xray', 'chest', 'lungs'],
  },
  {
    name: 'MRI — Brain (Plain)',
    slug: 'mri-brain-plain',
    category: 'imaging',
    sampleType: 'Imaging',
    homeCollectionAvailable: false,
    basePrice: 6500,
    turnaroundHrs: 24,
    parametersCount: 0,
    parameters: ['Cerebral Hemispheres', 'Brainstem', 'Cerebellum', 'Ventricular System'],
    prepInstructions:
      'Inform staff of any implants, pacemaker or dental braces. Zero metal on the body.',
    description:
      'Magnetic resonance imaging of the brain. Performed at the lab centre with advanced high-field scanners.',
    isPopular: false,
    tags: ['imaging', 'mri', 'brain', 'scan'],
  },

  // 2 CARE PLANS
  {
    name: 'Diabetes Care Plan',
    slug: 'diabetes-care-plan',
    category: 'plan',
    sampleType: 'Blood',
    homeCollectionAvailable: true,
    basePrice: 599,
    turnaroundHrs: 6,
    parametersCount: 4,
    frequency: 'Every 3 months',
    parameters: ['HbA1c', 'Fasting Blood Glucose', 'Post-Prandial Glucose', 'Urine Microalbumin'],
    prepInstructions: '12-hour fasting required each quarterly cycle.',
    description:
      'HbA1c plus fasting and post-prandial sugar, auto-booked every quarter with trending analytics. Cancel any time.',
    isPopular: true,
    tags: ['diabetes', 'subscription', 'quarterly', 'plan'],
  },
  {
    name: 'Thyroid Care Plan',
    slug: 'thyroid-care-plan',
    category: 'plan',
    sampleType: 'Blood',
    homeCollectionAvailable: true,
    basePrice: 449,
    turnaroundHrs: 12,
    parametersCount: 3,
    frequency: 'Every 3 months',
    parameters: ['TSH', 'Total T3', 'Total T4'],
    prepInstructions: 'Morning sample preferred each cycle.',
    description:
      'TSH, T3 and T4 on a quarterly schedule for ongoing dosage monitoring and metabolic health.',
    isPopular: false,
    tags: ['thyroid', 'subscription', 'quarterly', 'plan'],
  },
];

export const REAL_LABS = [
  {
    name: 'Sunrise Diagnostics',
    area: 'Rajpur Road',
    address: '14/2 Rajpur Road, Near Dilaram Chowk, Dehradun, Uttarakhand 248001',
    geo: {
      type: 'Point',
      coordinates: [78.0583, 30.3456],
    },
    serviceAreaPincodes: ['248001', '248009', '248003'],
    priceMultiplier: 1.0,
    turnaroundHrs: 6,
    isVerified: true,
    isOwned: false,
  },
  {
    name: 'Doon Path Labs',
    area: 'Ballupur Chowk',
    address: '88 Chakrata Road, Ballupur Chowk, Dehradun, Uttarakhand 248001',
    geo: {
      type: 'Point',
      coordinates: [78.0125, 30.334],
    },
    serviceAreaPincodes: ['248001', '248006', '248007'],
    priceMultiplier: 0.92,
    turnaroundHrs: 8,
    isVerified: true,
    isOwned: false,
  },
  {
    name: 'Himalaya Medicare',
    area: 'Clock Tower',
    address: '3 Paltan Bazaar, Clock Tower Circle, Dehradun, Uttarakhand 248001',
    geo: {
      type: 'Point',
      coordinates: [78.0418, 30.3256],
    },
    serviceAreaPincodes: ['248001', '248002', '248005'],
    priceMultiplier: 0.85,
    turnaroundHrs: 12,
    isVerified: true,
    isOwned: false,
  },
];

export default { REAL_TESTS, REAL_LABS };
